ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure("2") do |config|
  config.vm.synced_folder "..", "/microclock", type: "rsync"

  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.remains_running = false
    d.force_host_vm = true
  end
end
